### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by jeastman19** [pablomatiasgomez/agip-dv-chrome#1]
Hola Pablo, más que un issues, es para mostrarte cómo hice la parte que obtiene el Código de Validación

Código
--------
const dominio = 'USW621'

const tabla = {
  A: "14",
  B: "01",
  C: "00",
  D: "16",
  E: "05",
  F: "20",
  G: "19",
  H: "09",
  I: "24",
  J: "07",
  K: "21",
  L: "08",
  M: "04",
  N: "13",
  O: "25",
  P: "22",
  Q: "18",
  R: "10",
  S: "02",
  T: "06",
  U: "12",
  V: "23",
  W: "11",
  X: "03",
  Y: "15",
  Z: "17"
}

let digitos = dominio.split('').map( x => tabla[x] || x ).join('').split('').reverse()

let impares = digitos.reduce( (a, x, i) => i%2 ? a : a + Number(x), 0)
let pares = digitos.reduce( (a, x, i) => i%2 ? a + Number(x) : a, 0)
let cv = impares * 10 + pares

console.log(digitos)
console.log(impares)
console.log(pares)
console.log(cv)

Es la primera versión que hago, quizás luego la modifique más.

Saludos.

**Comment by pablomatiasgomez** [comment]
Hola! Muy bueno, realmente el codigo que hice yo lo hice hace bastante, asi que es probable que el tuyo sea mas reducido :)
De todos modos, te encontré un pequeño bug! cuando calculas los impares y pares, tenes que tener en cuenta que tenes que reducirlos hasta quedarte con un solo dígito. Por ejemplo para la patente `FAY097` esta dando `128` cuando en realidad debería ser `29`

**Comment by jeastman19** [comment]
Si, ya me di cuenta de ello, lo reviso y te comento

**Comment by jeastman19** [comment]
Ahí revisé y corregí el error
------
const dominio = 'FAY097'

const tabla = {
  A: "14",
  B: "01",
  C: "00",
  D: "16",
  E: "05",
  F: "20",
  G: "19",
  H: "09",
  I: "24",
  J: "07",
  K: "21",
  L: "08",
  M: "04",
  N: "13",
  O: "25",
  P: "22",
  Q: "18",
  R: "10",
  S: "02",
  T: "06",
  U: "12",
  V: "23",
  W: "11",
  X: "03",
  Y: "15",
  Z: "17"
}

let reduce = (valor) => {
  let digitos = valor.split('')

  let res = String( digitos.reduce( (a, v) => a + Number(v), 0 ) )

  if (res > 9) {
    res = reduce(res)
  }

  return res

}

let digitos = dominio.split('').map( x => tabla[x] || x ).join('').split('').reverse()

const impares = digitos.filter( (x, i) => i % 2 === 1 ).join('')
const pares = digitos.filter( (x, i) => i % 2 === 0 ).join('')

let = result = reduce(pares) + reduce(impares)
console.log(result)
